name: learn-github-actions
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  call-build-and-check:
   uses: .github/workflows/build-and-test.yml
  docker-beta:
    runs-on: ubuntu-latest
    needs: build-and-check
    steps:
        - name: Setup up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to github container registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.docker }}

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ghcr.io/${{ github.repository }}

        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ${{ steps.meta.outputs.tags }}
